### ISSUE TITLE
the version of chatGPT and dataset

### ISSUE THREAD

**Issue by Nie-Yingying** [shijing001/FFN_corpus#1]
Thanks for your excellent work!

May I know the version of chatGPT  used in your paper "FFN: a Fine-grained Chinese-English Financial Domain Parallel Corpus" ?
And could you share your processed dataset in "Mining an English-Chinese parallel Dataset of Financial News" ?

Thanks again!

**Comment by shijing001** [comment]
The version for ChatGPT is GPT-Turbo, the default one...
We may release the modified dataset later... sorry for the delay
